# Generated by Django 2.2.2 on 2019-06-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190615_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='brief',
            new_name='brief_content',
        ),
    ]
